Repository goblint/gobview, pull requests merged in 2024-02, with the labels that each got.

#9 Upgrade jsoo-react
  dune-project
  gobview.opam
  gobview.opam.locked
  gobview.opam.template
  src/App.re
  src/Graphviz.mli
  src/Main.re
  src/bindings/dune
  src/bindings/errorBoundary.mli
  src/bindings/monaco.mli
  src/dune
  src/gvConstants.ml
  src/react-requires.js
  src/ui/base/button.re
  src/ui/base/collapsibleList.re
  src/ui/base/collapsibleListItem.re
  src/ui/base/gvEditor.re
  src/ui/base/input.re
  src/ui/base/invalidFeedback.re
  src/ui/base/label.re
  src/ui/base/link.re
  src/ui/base/listInput.re
  src/ui/base/select.re
  src/ui/base/textArea.re
  src/ui/base/validatedInput.re
  src/ui/content/Content.re
  src/ui/content/gvBreadcrumb.re
  src/ui/content/gvFileView.re
  src/ui/content/gvFuncView.re
  src/ui/panel/DeadCodeView.re
  src/ui/panel/Panel.re
  src/ui/panel/ParameterView.re
  src/ui/panel/WarningView.re
  src/ui/panel/gvStatisticsView.re
  src/ui/search/searchExpressionBuilder.re
  src/ui/search/searchFindBuilder.re
  src/ui/search/searchKindBuilder.re
  src/ui/search/searchModeBuilder.re
  src/ui/search/searchQueryBuilder.re
  src/ui/search/searchQueryEditor.re
  src/ui/search/searchQueryView.re
  src/ui/search/searchResultView.re
  src/ui/search/searchStructureBuilder.re
  src/ui/search/searchTargetBuilder.re
  src/ui/search/searchView.re
  src/ui/sidebar/SidebarLeft.re
  src/ui/sidebar/SidebarRight.re
  src/ui/sidebar/gvFileList.re
  src/ui/state/gvAnalysesView.re
  src/ui/state/gvGlobalStateView.re
  src/ui/state/gvNodeStateView.re
  src/ui/state/gvRepresentationView.re
  src/utils/ErrorBoundary.ml
  src/utils/Graphviz.ml
  src/utils/utils.ml
Labels: enhancement, help wanted

#39 Adapt to removed `Libmaincil` module
  src/App.re
  src/dune
Labels: bug

#40 Adapt to `Logs` module in Goblint
  src/App.re
  src/ui/panel/gvStatisticsView.re
Labels: bug

#33 Serve files from separate distribution directory
  .gitignore
  dune
  goblint-http-server/dune
  goblint-http-server/goblint_http.ml
Labels: enhancement

#41 Adapt to `compute_cfg` move
  src/state/gvGoblint.ml
Labels: bug
